# Generated by Django 4.2.7 on 2023-12-05 00:55

import datetime
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_artisan_customer_material_order_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="material_id",
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.ForeignKey(
                default=uuid.uuid4,
                on_delete=models.CASCADE,
                related_name="products",
                to="base.material",
            ),
            preserve_default=False,
        ),
    ]
