# Generated by Django 4.2.7 on 2023-12-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_product_material_id_product_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_id",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default="123e4567-e89b-12d3-a456-426614174001",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="base.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                default="123e4567-e89b-12d3-a456-426614174001",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="base.order",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default="4fddb4a3-ab8f-42a2-86a0-e77d9f9995a2",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
